# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_commentmodel_likemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
